name: Docker image
on:
  push:
    branches:
      - '*'
    paths:
      - 'docker/**'
      - 'data/**'
      - '.github/workflows/docker-image.yaml'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'
    paths:
      - 'docker/**'
      - 'data/**'
      - '.github/workflows/docker-image.yaml'
jobs:
  build:
    name: Build & push docker image for ${{ matrix.postgres }}-${{ matrix.postgis }}-${{ matrix.mobilitydb }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { postgres: 18, postgis: 3.6, mobilitydb: 1.3 }

    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Info
        run: echo "Parameters. ${{ github.event.base_ref }}, ${{ github.ref_type }}, ${{ github.ref }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: mobilitydb/mobilitydb:${{ matrix.postgres }}-${{ matrix.postgis }}-${{ matrix.mobilitydb }}-workshop
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres }}
            POSTGIS_VERSION=${{ matrix.postgis }}
            MOBILITYDB_VERSION=${{ matrix.mobilitydb }}
